// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBFQWpInSV-hau2oBmLWiXaAro4TmjQOM',
    appId: '1:948990696227:web:1bff0a2b9008e0b4024a96',
    messagingSenderId: '948990696227',
    projectId: 'student-tracker-faa81',
    authDomain: 'student-tracker-faa81.firebaseapp.com',
    storageBucket: 'student-tracker-faa81.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQgcDlKs9VJu2s293oiXmzKUJRx4ZlPeg',
    appId: '1:948990696227:android:c64524abb26a3695024a96',
    messagingSenderId: '948990696227',
    projectId: 'student-tracker-faa81',
    storageBucket: 'student-tracker-faa81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA428_pRGoqWFdUWGTx2POtgWMtsTvBJgM',
    appId: '1:948990696227:ios:f2338798f9900fae024a96',
    messagingSenderId: '948990696227',
    projectId: 'student-tracker-faa81',
    storageBucket: 'student-tracker-faa81.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA428_pRGoqWFdUWGTx2POtgWMtsTvBJgM',
    appId: '1:948990696227:ios:f2338798f9900fae024a96',
    messagingSenderId: '948990696227',
    projectId: 'student-tracker-faa81',
    storageBucket: 'student-tracker-faa81.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBFQWpInSV-hau2oBmLWiXaAro4TmjQOM',
    appId: '1:948990696227:web:ee662afef873ed6f024a96',
    messagingSenderId: '948990696227',
    projectId: 'student-tracker-faa81',
    authDomain: 'student-tracker-faa81.firebaseapp.com',
    storageBucket: 'student-tracker-faa81.firebasestorage.app',
  );
}
